networks:
  default:
    driver: bridge

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    